#!/usr/bin/env sh
set -eu

SELF_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

cmd="${1:-}"

case "$cmd" in
  "")
    exec "$SELF_DIR/cloudagent" --help
    ;;
  help|--help|-h)
    CLOUDAGENT_RELEASE_MODE=1 exec "$SELF_DIR/cloudagent" --help
    ;;
  version|--version|-v)
    CLOUDAGENT_RELEASE_MODE=1 exec "$SELF_DIR/cloudagent" --version
    ;;
  start|status|stop|cli|platform|node)
    CLOUDAGENT_RELEASE_MODE=1 exec "$SELF_DIR/cloudagent" "$@"
    ;;
  *)
    CLOUDAGENT_RELEASE_MODE=1 exec "$SELF_DIR/cloudagent" "$@"
    ;;
esac
